# Generated by Django 4.1 on 2022-09-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=256)),
                ('alegia_Glt', models.BooleanField(default=True)),
                ('alegia_Lct', models.BooleanField(default=True)),
                # ('data_nascimento', models.DateTimeField(null=True)),
                ('idade', models.IntegerField()),
            ],
        ),
    ]
