# Generated by Django 4.1 on 2022-09-02 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='alegia_Glt',
            new_name='alegia_Gluten',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='alegia_Lct',
            new_name='alegia_Lactose',
        ),
    ]
