# Generated by Django 4.1 on 2022-09-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0003_rename_alegia_gluten_profile_intolerancia_a_gluten_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='intolerancia_a_Gluten',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='intolerancia_a_Lactose',
            field=models.BooleanField(default=False),
        ),
    ]
